### ISSUE TITLE
`SELECT .. JOIN` support

### ISSUE THREAD

**Issue by penberg** [penberg/limbo#110]

**Comment by penberg** [comment]
We now have `WHERE` clause support, which should be useful for implementing this.

**Comment by jussisaurio** [comment]
first pass here https://github.com/penberg/limbo/pull/143

**Comment by penberg** [comment]
@jussisaurio I think we can probably close this now that #204 is merged? Sure there may be bugs, but the bulk of joins is now done?

**Comment by jussisaurio** [comment]
Yeah I mean some weirdos use RIGHT JOIN etc so we need to do those too, but separate issues are probably fine for those
