### ISSUE TITLE
`WHERE` clause logical operator support

### ISSUE THREAD

**Issue by penberg** [penberg/limbo#123]
Let's add support for things like `AND`, `OR`, etc. in `WHERE` clauses

**Comment by penberg** [comment]
@Feilkin @jussisaurio FYI

**Comment by Feilkin** [comment]
on it 🫡

**Comment by Feilkin** [comment]
nvm this seems to have already been implemented?

**Comment by penberg** [comment]
Aah, you're right @Feilkin, fixed in 3a55f1ffa934b689fbd6f366f8b8af0fcb5fb026. Closing.

**Comment by penberg** [comment]
@Feilkin but please note that, for example, https://github.com/penberg/limbo/issues/154 is still open so i think there's still work to do on `WHERE`
