### ISSUE TITLE
Date and time function support

### ISSUE THREAD

**Issue by penberg** [penberg/limbo#158]
This is a tracking issue for all date and time functions: https://github.com/penberg/limbo/blob/main/COMPAT.md#date-and-time-functions

**Comment by gvos94** [comment]
Will take a shot at implementing the date() function.

**Comment by sonhmai** [comment]
adding partial support for `time(..)` in https://github.com/penberg/limbo/pull/252

**Comment by sonhmai** [comment]
Adding some more guidelines for others.

[PR 252](https://github.com/penberg/limbo/commit/e6985c1380ca97527f89433e08aa579a05f968aa#diff-a046d58ab24eee8207f0ce3199f8d0a609edcef9c24b8ed7f242f7a60e6c1e61) can serve as an example of adding time() without modifier.

The test can be added to `testing/scalar-functions.test` and executed with `make test`.

The tests from sqlite can be referenced below (example for unixepoch)
- https://github.com/sqlite/sqlite/blob/f2b21a5f57e1a1db1a286c42af40563077635c3d/test/date3.test#L36
- https://github.com/sqlite/sqlite/blob/f2b21a5f57e1a1db1a286c42af40563077635c3d/test/date.test#L604
