### ISSUE TITLE
Switch to `lemon-rs` for parsing?

### ISSUE THREAD

**Issue by penberg** [penberg/limbo#163]
The `sqlite3-parser` crate we use for SQL parsing is surprisingly slow. Let's look into using `lemon-rs` like libSQL does, which may be faster.

**Comment by adiSuper94** [comment]
Hi @penberg I'd like to take a crack at this.

**Comment by penberg** [comment]
Let's wait to see what happens with https://github.com/gwenn/lemon-rs/pull/57 first. If it's merged, this issue is essentially resolved.

**Comment by pereman2** [comment]
sqlite3-parser == lemon-rs right?

**Comment by penberg** [comment]
I think lemon-rs has a lower level API than the one we use, but can be wrong too

**Comment by pereman2** [comment]
https://crates.io/crates/sqlite3-parser look at repo

**Comment by penberg** [comment]
Obsoleted by https://github.com/penberg/limbo/issues/185
