### ISSUE TITLE
Support the use of Aggregate Functions in Scalar Functions

### ISSUE THREAD

**Issue by JeanArhancet** [penberg/limbo#195]
The current implementation lacks support for utilizing aggregate functions within scalar functions, such as in the query `select length(max(id));`

**Comment by JeanArhancet** [comment]
I would like to work on this PR.

**Comment by jussisaurio** [comment]
This works now after #309 :

´´´
limbo> select length(max(id)) from users;
5
´´´

As you encounter specific issues with this feat, open separate issues from them!
