### ISSUE TITLE
Limbo acquires database file lock by default 

### ISSUE THREAD

**Issue by seonWKim** [penberg/limbo#302]
### Question 
Should we change current implementation of acquiring of lock when opening the database file? 

### Limbo implementation vs SQLite implementation 
The impelmentations of `IO`'s `open_file` acquires the database file lock by default. As a result, we are not able to open multiple connections like below 

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/8cd7875c-14f7-45cb-aea3-f2342f0a46e3">

The current implementation of SQLite seems to not acquire lock while opening the DB(It seems to acquire the database lock on non-SELECT transactions etc) 
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/56e39113-8e13-48fa-b6df-868fbc596c07">

### Reference ([SQLite Database System Design and Implementation (2nd Edition)](https://books.google.fi/books/?id=yWzwCwAAQBAJ&redir_esc=y))
![image](https://github.com/user-attachments/assets/5d0335a9-84b6-42c2-8f9b-3e1a688cb9ce)

**Comment by penberg** [comment]
@seonWKim We picked `PRAGMA locking_mode = EXCLUSIVE` as the default because it's the fastest one. With `NORMAL` (i guess same as NOLOCK there), the problem is that every transaction has to do a fcntl(), which is a round-trip to the kernel...

**Comment by seonWKim** [comment]
Oh I see. Will future implementation of transactions in limbo would not use `fcntl()` then?

**Comment by penberg** [comment]
Yes, exactly. Limbo would not need `fcntl()` in the transaction hot-path.
