### ISSUE TITLE
NextAwait's next instruction doesn't match that of SQLite

### ISSUE THREAD

**Issue by arpit-saxena** [penberg/limbo#351]
![image](https://github.com/user-attachments/assets/ff2a2e62-8608-4fb6-b616-96b68c7195e6)

In the above side-by-side comparison of the same database run in Limbo on the LHS and SQLite3 on the RHS, note that NextAsync's next command is RewindAwait. For SQLite, Next's next command is Column which makes sense that we do that when there are rows left.

I'll try and fix this. Let me know if this is expected for some reason

**Comment by jussisaurio** [comment]
Yeah I've noticed that, pretty sure it's not expected, go ahead and fix

**Comment by jussisaurio** [comment]
@arpit-saxena when you do this can you rename ´rewind_labels´ to something else (i think thats how the next backward jumps are called in the code atm)
