### ISSUE TITLE
`SELECT .. WHERE` support

### ISSUE THREAD

**Issue by penberg** [penberg/limbo#80]
Add support for `SELECT .. WHERE` filtering.

**Comment by Feilkin** [comment]
I could take a shot at this! Looking at some queries, it seems that all sqlite does is compile the WHERE expr body into a boolean expression, and inserts that into the bytecode with relevant branching to skip the row if the condition evaluates to false.

Sqlite also seems to do some optimizations for some expression, for example `WHERE id > 5` generates only a `SeekGT` (and an `Integer` after the program). I assume these optimizations can be left for a later date?

**Comment by penberg** [comment]
@Feilkin Go for it! Yes, let's leave optimizations for later.

**Comment by jussisaurio** [comment]
@Feilkin I'm sorry, your comment wasn't here earlier today and I started implementing this, mostly just to understand wth was going on in the code. Ended up with https://github.com/penberg/limbo/pull/121

Hope it's ok, I literally just didn't look at github until I was mostly done with this. Could've obviously expressed my intent to try to implement this here earlier, but to be honest I understood so little of the code initially that I had low confidence I would end up with anything worth pushing

**Comment by penberg** [comment]
No worries, it happens. I am sure there is bunch of things even for WHERE to still improve upon!

**Comment by penberg** [comment]
Initial pass done in c01e9b43418a30400e7deb4bdc5a570ccde68442. Closing this, but let's open new ones as issues pop up. I am sure there's still lots of work to be done here.
