### ISSUE TITLE
More aggregate functions

### ISSUE THREAD

**Issue by penberg** [penberg/limbo#93]
We have machinery for aggregate functions, but only `sum()` and `avg()` are implemented now. Let's add support for rest of the aggregate functions:

https://github.com/penberg/limbo/blob/main/docs/sqlite-compat.md#aggregate-functions

**Comment by vivek378521** [comment]
I have raised a PR: https://github.com/penberg/limbo/pull/100 for the aggregate function: count

Please review once. I am also attaching a screenshot of the count fn:
![Screenshot 2024-07-08 at 1 52 56 PM](https://github.com/penberg/limbo/assets/29369111/fdd7ed23-8212-474b-837d-df435ef43666)

**Comment by mazchew** [comment]
Hi @penberg! I've raised a [PR](https://github.com/penberg/limbo/pull/105) to try and implement the `max` aggregate function. I'm new to rust and contributing to database systems in general, do let me know if there is anything I can improve on!

![image](https://github.com/penberg/limbo/assets/61624815/d0d7be88-7096-40d3-9a2d-9fe8903da998)

Thank you!

**Comment by penberg** [comment]
We now support all aggregate functions. Closing the issue, thanks everyone!
